### ISSUE TITLE
rules of probability?

### ISSUE THREAD

**Issue by zapataf** [caseywdunn/phylogenetic_biology#27]
https://github.com/caseywdunn/phylogenetic_biology/blob/d638f89fd77b42821cca5267fa892dfdd8be5d96/04-inference.Rmd#L197

Not sure if you want to add here (a few line above) the "rules of probability": when events are `and` == `multiplication`, when events are `or` == `summation`. This mnemonic works for me.

**Comment by caseywdunn** [comment]
You read my mind. I will go over this in lecture today, but should consider adding a more explicit treatment here. Tried to gloss over it to keep things moving, but this is insufficient.

**Comment by caseywdunn** [comment]
Going to add an appendix to consolidate probability theory explanation. Best to have joint, exclusive, and conditional all explained in one place rather than scattered throughout book.

First need to get set up for creating appendices. First going to change to this style of ordering rmds in book:

https://github.com/hadley/r4ds/blob/master/_bookdown.yml

Then going to add appendices as described here:

https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers

Also, switch to explicit section labels for referring to sections, eg https://github.com/hadley/r4ds/blob/04d2eebbef5dc688e3d79b496bcf2609e7800692/communicate.Rmd#L3

**Comment by caseywdunn** [comment]
The alternative approaches to ordering are described here - https://bookdown.org/yihui/bookdown/usage.html#usage
